# Generated by Django 5.2 on 2025-05-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'وضعیت ملک',
                'verbose_name_plural': 'وضعیت های ملک',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'نوع ملک',
                'verbose_name_plural': 'انواع ملک',
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'نوع معامله',
                'verbose_name_plural': 'انواع معامله',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='کد ملک')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('address', models.TextField(verbose_name='آدرس کامل')),
                ('area', models.PositiveIntegerField(verbose_name='متراژ (متر مربع)')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('year_built', models.PositiveIntegerField(verbose_name='سال ساخت')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='تعداد اتاق')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='تصویر اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertystatus', verbose_name='وضعیت')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype', verbose_name='نوع ملک')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.transactiontype', verbose_name='نوع معامله')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
                'ordering': ['-created_at'],
            },
        ),
    ]
