# Generated by Django 5.2 on 2025-05-07 16:07

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', validators=[properties.models.secure_upload_validator], verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_images/', validators=[properties.models.secure_upload_validator], verbose_name='تصویر'),
        ),
    ]
