# Generated by Django 5.2 on 2025-05-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='بالکن'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='آسانسور'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_package',
            field=models.BooleanField(default=False, verbose_name='سیستم گرمایشی پکیج'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_warehouse',
            field=models.BooleanField(default=False, verbose_name='انباری'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_renovated',
            field=models.BooleanField(default=False, verbose_name='بازسازی شده'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
