# Generated by Django 5.2 on 2025-05-07 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(default='سیستم هوشمند مدیریت املاک هیرو', max_length=100, verbose_name='عنوان وب\u200cسایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='لوگو')),
                ('default_property_image', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='تصویر پیش\u200cفرض املاک')),
                ('font_type', models.CharField(choices=[('vazir', 'فونت وزیر'), ('iransans', 'فونت ایران سنس')], default='vazir', max_length=20, verbose_name='نوع فونت')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد توسط')),
            ],
            options={
                'verbose_name': 'سابقه پشتیبان\u200cگیری',
                'verbose_name_plural': 'سوابق پشتیبان\u200cگیری',
                'ordering': ['-created_at'],
            },
        ),
    ]
