# Generated by Django 5.2 on 2025-05-07 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='company_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دفتر'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل تماس'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت/آژانس'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_dark_mode',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی حالت تاریک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_property_comments',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی نظرات'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_sms_notifications',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی اطلاع\u200cرسانی پیامکی'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='آیکون سایت'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='maintenance_message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام حالت تعمیر و نگهداری'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='حالت تعمیر و نگهداری'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='price_unit',
            field=models.CharField(choices=[('toman', 'تومان'), ('rial', 'ریال'), ('dollar', 'دلار')], default='toman', max_length=20, verbose_name='واحد قیمت'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='primary_color',
            field=models.CharField(choices=[('blue', 'آبی'), ('green', 'سبز'), ('red', 'قرمز'), ('purple', 'بنفش'), ('orange', 'نارنجی'), ('teal', 'فیروزه\u200cای')], default='blue', max_length=20, verbose_name='رنگ اصلی سیستم'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='property_per_page',
            field=models.PositiveIntegerField(default=10, verbose_name='تعداد املاک در هر صفحه'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='show_property_views',
            field=models.BooleanField(default=True, verbose_name='نمایش تعداد بازدیدها'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='site_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='site_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تلگرام'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره واتس\u200cاپ'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='font_type',
            field=models.CharField(choices=[('vazir', 'فونت وزیر'), ('iransans', 'فونت ایران سنس'), ('sahel', 'فونت ساحل')], default='vazir', max_length=20, verbose_name='نوع فونت'),
        ),
    ]
