# Generated by Django 5.2 on 2025-05-07 16:07

import config.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_systemconfig_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprecord',
            name='file_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255), config.models.validate_no_script, config.models.validate_file_path], verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='company_address',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500), config.models.validate_no_script], verbose_name='آدرس دفتر'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='ایمیل وارد شده معتبر نیست')], verbose_name='ایمیل تماس'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100), config.models.validate_no_script], verbose_name='نام شرکت/آژانس'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید فقط شامل اعداد و حداکثر یک علامت + باشد', regex='^\\+?[0-9]{8,15}$')], verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='آدرس وارد شده معتبر نیست')], verbose_name='آدرس اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='maintenance_message',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000), config.models.validate_no_script], verbose_name='پیام حالت تعمیر و نگهداری'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='site_description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000), config.models.validate_no_script], verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='site_keywords',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500), config.models.validate_no_script], verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='آدرس وارد شده معتبر نیست')], verbose_name='آدرس تلگرام'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='website_title',
            field=models.CharField(default='سیستم هوشمند مدیریت املاک هیرو', max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(100), config.models.validate_no_script], verbose_name='عنوان وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='شماره واتس\u200cاپ باید فقط شامل اعداد و حداکثر یک علامت + باشد', regex='^\\+?[0-9]{9,15}$')], verbose_name='شماره واتس\u200cاپ'),
        ),
    ]
