# Generated by Django 5.2 on 2025-05-08 11:02

import config.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_backuprecord_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='aparat_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='آدرس وارد شده معتبر نیست')], verbose_name='آدرس آپارات'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='area_unit',
            field=models.CharField(choices=[('meter', 'متر مربع'), ('foot', 'فوت مربع')], default='meter', max_length=20, verbose_name='واحد متراژ'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='business_hours',
            field=models.CharField(blank=True, help_text='مثال: شنبه تا چهارشنبه 9 الی 17', max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100), config.models.validate_no_script], verbose_name='ساعات کاری'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='cache_timeout',
            field=models.PositiveIntegerField(default=3600, help_text='مدت زمان ذخیره\u200cسازی کش صفحات (3600 = یک ساعت)', verbose_name='زمان کش (ثانیه)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='canonical_domain',
            field=models.URLField(blank=True, help_text='برای تنظیم لینک canonical (مثال: https://example.com)', null=True, verbose_name='دامنه اصلی سایت'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_fax',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='شماره فکس باید فقط شامل اعداد و حداکثر یک علامت + باشد', regex='^\\+?[0-9]{8,15}$')], verbose_name='شماره فکس'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='default_sort_properties',
            field=models.CharField(choices=[('newest', 'جدیدترین'), ('price_low', 'ارزان\u200cترین'), ('price_high', 'گران\u200cترین'), ('area_high', 'بزرگترین'), ('views', 'پربازدیدترین')], default='newest', max_length=20, verbose_name='مرتب\u200cسازی پیش\u200cفرض املاک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_animations',
            field=models.BooleanField(default=True, verbose_name='فعال\u200cسازی انیمیشن\u200cها'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_back_to_top',
            field=models.BooleanField(default=True, verbose_name='دکمه بازگشت به بالا'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_compare',
            field=models.BooleanField(default=True, verbose_name='فعال\u200cسازی مقایسه املاک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_csp',
            field=models.BooleanField(default=True, help_text='افزایش امنیت با محدود کردن منابع مجاز', verbose_name='فعال\u200cسازی Content Security Policy'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_email_notifications',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی اطلاع\u200cرسانی ایمیلی'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_favorites',
            field=models.BooleanField(default=True, verbose_name='فعال\u200cسازی لیست علاقه\u200cمندی\u200cها'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_hsts',
            field=models.BooleanField(default=True, help_text='اجبار اتصال HTTPS برای افزایش امنیت', verbose_name='فعال\u200cسازی HSTS'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_http2_push',
            field=models.BooleanField(default=False, help_text='بهبود سرعت بارگذاری صفحات', verbose_name='فعال\u200cسازی HTTP/2 Push'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_pdf_export',
            field=models.BooleanField(default=True, verbose_name='فعال\u200cسازی خروجی PDF'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_print_listing',
            field=models.BooleanField(default=True, verbose_name='فعال\u200cسازی چاپ مشخصات ملک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_property_rating',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی امتیازدهی به املاک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_property_sharing',
            field=models.BooleanField(default=True, verbose_name='فعال\u200cسازی اشتراک\u200cگذاری املاک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_rtl_switch',
            field=models.BooleanField(default=False, verbose_name='امکان تغییر جهت راست/چپ'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_structured_data',
            field=models.BooleanField(default=True, help_text='بهینه\u200cسازی برای نمایش بهتر در نتایج گوگل', verbose_name='فعال\u200cسازی داده ساختاریافته'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='آدرس وارد شده معتبر نیست')], verbose_name='آدرس فیسبوک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='footer_style',
            field=models.CharField(choices=[('default', 'پیش\u200cفرض'), ('simple', 'ساده'), ('dark', 'تیره'), ('colored', 'رنگی')], default='default', max_length=20, verbose_name='سبک فوتر'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='footer_text',
            field=models.TextField(blank=True, help_text='توضیحات پایین صفحه که در همه صفحات نمایش داده می\u200cشود', null=True, validators=[django.core.validators.MaxLengthValidator(500), config.models.validate_no_script], verbose_name='متن فوتر سایت'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='مثال: UA-123456789-1 یا G-XXXXXXXXXX', max_length=50, null=True, verbose_name='شناسه گوگل آنالیتیکس'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='google_maps_embed',
            field=models.TextField(blank=True, help_text='کد iframe گوگل مپ برای نمایش موقعیت دفتر', null=True, verbose_name='کد جاسازی نقشه گوگل'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='google_search_console',
            field=models.CharField(blank=True, help_text='کد تأیید مالکیت سایت در گوگل سرچ کنسول', max_length=100, null=True, verbose_name='کد تأیید گوگل سرچ کنسول'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='مثال: GTM-XXXXXXX', max_length=50, null=True, verbose_name='شناسه گوگل تگ منیجر'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='layout_style',
            field=models.CharField(choices=[('default', 'پیش\u200cفرض'), ('boxed', 'جعبه\u200cای'), ('fluid', 'کامل عرض'), ('compact', 'فشرده')], default='default', max_length=20, verbose_name='نوع چیدمان صفحه'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='آدرس وارد شده معتبر نیست')], verbose_name='آدرس لینکدین'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='logo_footer',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='لوگوی فوتر'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='navbar_style',
            field=models.CharField(choices=[('default', 'پیش\u200cفرض'), ('gradient', 'گرادیانت'), ('transparent', 'شفاف'), ('dark', 'تیره'), ('light', 'روشن'), ('colored', 'رنگی')], default='default', max_length=20, verbose_name='سبک منوی اصلی'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='property_card_style',
            field=models.CharField(choices=[('default', 'پیش\u200cفرض'), ('compact', 'فشرده'), ('grid', 'شبکه\u200cای'), ('list', 'لیستی'), ('modern', 'مدرن')], default='default', max_length=20, verbose_name='سبک کارت املاک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='secondary_color',
            field=models.CharField(choices=[('blue', 'آبی'), ('green', 'سبز'), ('red', 'قرمز'), ('purple', 'بنفش'), ('orange', 'نارنجی'), ('teal', 'فیروزه\u200cای'), ('indigo', 'نیلی'), ('pink', 'صورتی')], default='teal', max_length=20, verbose_name='رنگ ثانویه سیستم'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='show_price_format',
            field=models.CharField(choices=[('normal', 'معمولی (۱۰۰۰۰۰۰)'), ('formatted', 'فرمت\u200cشده (۱,۰۰۰,۰۰۰)'), ('abbreviated', 'خلاصه (۱ میلیون)'), ('text', 'متنی (یک میلیون تومان)')], default='formatted', max_length=20, verbose_name='نحوه نمایش قیمت'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sms_api_key',
            field=models.CharField(blank=True, help_text='کلید API سرویس پیامک', max_length=100, null=True, verbose_name='کلید API پیامک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sms_line_number',
            field=models.CharField(blank=True, help_text='شماره خط ارسال پیامک', max_length=20, null=True, verbose_name='شماره خط پیامکی'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='آدرس سرور SMTP برای ارسال ایمیل', max_length=100, null=True, verbose_name='هاست SMTP'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز عبور SMTP'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, help_text='معمولاً 587 یا 465', null=True, verbose_name='پورت SMTP'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری SMTP'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='ایمیل وارد شده معتبر نیست')], verbose_name='ایمیل پشتیبانی'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='آدرس وارد شده معتبر نیست')], verbose_name='آدرس توییتر'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='use_ssl_email',
            field=models.BooleanField(default=True, verbose_name='استفاده از SSL برای ایمیل'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='آدرس وارد شده معتبر نیست')], verbose_name='آدرس یوتیوب'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='font_type',
            field=models.CharField(choices=[('vazir', 'فونت وزیر'), ('iransans', 'فونت ایران سنس'), ('sahel', 'فونت ساحل'), ('estedad', 'فونت استعداد'), ('yekan', 'فونت یکان')], default='vazir', max_length=20, verbose_name='نوع فونت'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='price_unit',
            field=models.CharField(choices=[('toman', 'تومان'), ('rial', 'ریال'), ('dollar', 'دلار'), ('euro', 'یورو'), ('dirham', 'درهم')], default='toman', max_length=20, verbose_name='واحد قیمت'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='primary_color',
            field=models.CharField(choices=[('blue', 'آبی'), ('green', 'سبز'), ('red', 'قرمز'), ('purple', 'بنفش'), ('orange', 'نارنجی'), ('teal', 'فیروزه\u200cای'), ('indigo', 'نیلی'), ('pink', 'صورتی')], default='blue', max_length=20, verbose_name='رنگ اصلی سیستم'),
        ),
    ]
