# Generated by Django 5.2 on 2025-05-08 23:07

import config.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_systemconfig_aparat_url_systemconfig_area_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='property_contact_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='config/contacts/', verbose_name='تصویر مشاور'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='property_contact_email',
            field=models.EmailField(blank=True, help_text='ایمیل نمایش داده شده در صفحه جزئیات ملک', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='ایمیل وارد شده معتبر نیست')], verbose_name='ایمیل مشاور'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='property_contact_mobile',
            field=models.CharField(blank=True, help_text='شماره موبایل نمایش داده شده در صفحه جزئیات ملک', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید فقط شامل اعداد و حداکثر یک علامت + باشد', regex='^\\+?[0-9]{8,15}$')], verbose_name='شماره موبایل'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='property_contact_name',
            field=models.CharField(blank=True, help_text='نام نمایش داده شده در بخش اطلاعات تماس جزئیات ملک', max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100), config.models.validate_no_script], verbose_name='نام مشاور املاک'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='property_contact_phone',
            field=models.CharField(blank=True, help_text='شماره تماس ثابت نمایش داده شده در صفحه جزئیات ملک', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید فقط شامل اعداد و حداکثر یک علامت + باشد', regex='^\\+?[0-9]{8,15}$')], verbose_name='شماره تماس ثابت'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='property_contact_position',
            field=models.CharField(blank=True, help_text='مثال: کارشناس فروش و اجاره', max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100), config.models.validate_no_script], verbose_name='عنوان شغلی مشاور'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='property_contact_whatsapp',
            field=models.CharField(blank=True, help_text='شماره واتس\u200cاپ برای تماس در صفحه جزئیات ملک (اگر با موبایل متفاوت است)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='شماره واتس\u200cاپ باید فقط شامل اعداد و حداکثر یک علامت + باشد', regex='^\\+?[0-9]{8,15}$')], verbose_name='واتس\u200cاپ مشاور'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='show_property_contact_info',
            field=models.BooleanField(default=True, help_text='فعال یا غیرفعال کردن بخش اطلاعات تماس در صفحه جزئیات ملک', verbose_name='نمایش اطلاعات تماس مشاور'),
        ),
    ]
