# Generated by Django 5.2 on 2025-05-10 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_systemconfig_property_contact_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='backup_type',
            field=models.CharField(choices=[('full', 'پشتیبان کامل'), ('data_only', 'فقط داده\u200cها'), ('media_only', 'فقط فایل\u200cهای مدیا'), ('config_only', 'فقط تنظیمات'), ('custom', 'سفارشی')], default='full', max_length=20, verbose_name='نوع پشتیبان'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='چک\u200cسام'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='compression_level',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='سطح فشرده\u200cسازی'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='is_encrypted',
            field=models.BooleanField(default=False, verbose_name='رمزنگاری شده'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['created_at'], name='config_back_created_e50ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['backup_type'], name='config_back_backup__5e6f44_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['created_by'], name='config_back_created_3d515d_idx'),
        ),
    ]
